services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-dev
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT_NAME=localhost
      - CONFIG=config.Develop
      - BUILD_VERSION=local
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - S3_ENDPOINT=http://s3:9000
      - S3_EXPORT_BUCKET=export
      - S3_SOURCE_BUCKET_MERLIN=merlin
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - 65491:8080
    volumes:
      - ./:/app
    depends_on:
      - s3
    healthcheck:
      start_period: 10s
      start_interval: 2s

  s3:
    image: scireum/s3-ninja
    ports:
      - 65490:9000
    volumes:
      - s3data:/home/sirius/data

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65492:8000

volumes:
  s3data:
