services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-dev
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT_NAME=localhost
      - CONFIG=config.Develop
      - BUILD_VERSION=local
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - S3_EXPORT_LOCATION=s3://my-bucket.s3.us-east-1.amazonaws.com
      - S3_MERLIN_SOURCES=s3://my-bucket.s3.us-east-1.amazonaws.com/merlin-sources/
    ports:
      - 65491:8080
    volumes:
      - ./:/app
    healthcheck:
      start_period: 10s
      start_interval: 2s

  s3:
    image: quay.io/minio/minio:latest
    command: minio server /data
    ports:
      - "65490:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
      MINIO_DOMAIN: s3.us-east-1.amazonaws.com
    restart: always
    networks:
      default:
        aliases:
          - my-bucket.s3.us-east-1.amazonaws.com

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65492:8000
