name: Run Python tests

runs:
  using: "composite"
  steps:
    - name: Start app container
      run: docker compose up --detach --wait --wait-timeout 300 app || docker compose logs app
      shell: bash
    - name: Create buckets
      run: ./test/create-empty-buckets.sh
      shell: bash
    - name: Add files to buckets
      run: |
        AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY aws s3 cp src s3://merlin/ --recursive --endpoint-url http://localhost:65490
      shell: bash
    - name: Run a packager
      run: docker compose exec app poetry run python tasks/process.py merlin all
      shell: bash
    - name: Show the JSON manifest
      run: |
        AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY aws s3 cp s3://export/merlin/manifest.json ./manifest.json --endpoint-url http://localhost:65490
        AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY aws s3 cp s3://export/merlin/all.zip ./all.zip --endpoint-url http://localhost:65490
        test -f ./manifest.json
        test -f ./all.zip
        cat ./manifest.json
      shell: bash
