name: Run Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: run-lambda-${{ github.ref }}

jobs:
  test-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-region: eu-west-2
          role-to-assume: TODO
          role-session-name: TODO

      - name: Run Lambda function
        run: |
          PAYLOAD=
          RESPONSE=$(aws lambda invoke --function-name TODO --payload "$PAYLOAD" response.json --log-type Tail --query 'StatusCode' --output text --cli-read-timeout 0)
          echo "Lambda function response: $RESPONSE"
          cat response.json
          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "Failed to trigger the lambda function"
            exit 1
          fi
        # TODO: Run the deployed lambda (from aws/lambda/batch-zip-merlin-files.py)
