name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-lambda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-region: eu-west-2
          role-to-assume: TODO
          role-session-name: TODO

      - name: Deploy Lambda
        uses: aws-actions/aws-lambda-deploy@d496277188b89f0be02d7a2216fc912c0427702a # v1.0.0
        with:
          function-name: batch-zip-merlin-files
          code-artifacts-dir: aws/lambda
          handler: batch-zip-merlin-files.lambda_handler
          runtime: python3.14
